{"name": "Получение заказа авторизованного пользователя", "status": "broken", "statusDetails": {"message": "KeyError: 'accessToken'", "trace": "@pytest.fixture\n    def user_token():\n        payload = helpers.payload\n        response = requests.post(EndpointsUrl.CREATE_USER, data=payload)\n>       token = response.json()['accessToken']\nE       KeyError: 'accessToken'\n\nconftest.py:31: KeyError"}, "start": 1709682739005, "stop": 1709682739005, "uuid": "17337006-4dfa-4fe9-977f-db5332a355c3", "historyId": "baa7c46917b31cc9dd66d3f5061b882c", "testCaseId": "baa7c46917b31cc9dd66d3f5061b882c", "fullName": "tests.test_get_order.TestApiGetUserOrders#test_auth_user_get_order_successful", "labels": [{"name": "feature", "value": "Проверяем получение заказа пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order"}, {"name": "subSuite", "value": "TestApiGetUserOrders"}, {"name": "host", "value": "DESKTOP-AQ71LTK"}, {"name": "thread", "value": "10516-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order"}]}