{"name": "Тест авторизации с неверным логином", "status": "broken", "statusDetails": {"message": "KeyError: 'accessToken'", "trace": "self = <allure_commons._allure.fixture object at 0x0000027741C30910>, args = (), kwargs = {}\n\n    def __call__(self, *args, **kwargs):\n        self.parameters = func_parameters(self._fixture_function, *args, **kwargs)\n    \n        with self:\n>           return self._fixture_function(*args, **kwargs)\n\nvenv\\lib\\site-packages\\allure_commons\\_allure.py:221: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    @pytest.fixture\n    def user_data():\n        payload = helpers.payload\n        response = requests.post(EndpointsUrl.CREATE_USER, data=payload)\n    \n        yield payload\n>       token = response.json()['accessToken']\nE       KeyError: 'accessToken'\n\nconftest.py:23: KeyError"}, "start": 1709682740062, "stop": 1709682740222, "uuid": "9feb9849-558d-4d26-b1d9-0a1362f79c01", "historyId": "27943f6730ab4d740c33daa26147545a", "testCaseId": "27943f6730ab4d740c33daa26147545a", "fullName": "tests.test_login_user.TestLoginUser#test_login_user_incorrect_email_error", "labels": [{"name": "feature", "value": "Проверяем авторизацию пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-AQ71LTK"}, {"name": "thread", "value": "10516-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}